server:
  port: 8000

spring:
  application:
    name: apigateway-service
  config:
    import: optional:configserver:http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8888
  profiles:
    active: dev
  cloud:
    config:
      name: secret
    gateway:
      routes:
        # user-service routing
        # Jwt Filter X
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/refresh
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/oauth2/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # Jwt Filter O
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/v1/members/**
            - Method=GET, POST, PUT, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - JwtFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #til-service routing
        # Jwt Filter O
        - id: til-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/til-service/api/v1/boards/**
            - Method=GET, POST, PUT, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - JwtFilter
            - RewritePath=/til-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-15-164-164-245.ap-northeast-2.compute.amazonaws.com:8761/eureka

#logging:
#  level:
#    propofol:
#      apigateway: debug
